=== JavaDim/stackkataproject/src/test/resources/datasets/testresourceusercontroller/database.dtd
<!ELEMENT dataset (user_entity| votes_on_answers| votes_on_questions| reputation| answer| question| role)*>
        <!ELEMENT user_entity (#PCDATA)>
        <!ATTLIST user_entity
                id CDATA #REQUIRED
                about CDATA #REQUIRED
                city CDATA #REQUIRED
                email CDATA #REQUIRED
                full_name CDATA #REQUIRED
                image_link CDATA #REQUIRED
                is_deleted CDATA #REQUIRED
                is_enabled CDATA #REQUIRED
                last_redaction_date CDATA #REQUIRED
                link_github CDATA #REQUIRED
                link_site CDATA #REQUIRED
                link_vk CDATA #REQUIRED
                nickname CDATA #REQUIRED
                password CDATA #REQUIRED
                persist_date CDATA #REQUIRED
                role_id CDATA #REQUIRED>

        <!ELEMENT votes_on_answers (#PCDATA)>
        <!ATTLIST votes_on_answers
                answer_id CDATA #REQUIRED
                id CDATA #REQUIRED
                persist_date CDATA #REQUIRED
                user_id CDATA #REQUIRED
                vote_type CDATA #REQUIRED>

        <!ELEMENT votes_on_questions (#PCDATA)>
        <!ATTLIST votes_on_questions
                id CDATA #REQUIRED
                persist_date CDATA #REQUIRED
                question_id CDATA #REQUIRED
                user_id CDATA #REQUIRED
                vote_typeq CDATA #REQUIRED>

        <!ELEMENT reputation (#PCDATA)>
        <!ATTLIST reputation
                answer_id CDATA #REQUIRED
                author_id CDATA #REQUIRED
                count CDATA #REQUIRED
                id CDATA #REQUIRED
                persist_date CDATA #REQUIRED
                question_id CDATA #REQUIRED
                sender_id CDATA #REQUIRED
                type CDATA #REQUIRED>

        <!ELEMENT answer (#PCDATA)>
        <!ATTLIST answer
                id CDATA #REQUIRED
                date_accept_time CDATA #REQUIRED
                html_body CDATA #REQUIRED
                is_deleted CDATA #REQUIRED
                is_deleted_by_moderator CDATA #REQUIRED
                is_helpful CDATA #REQUIRED
                persist_date CDATA #REQUIRED
                update_date CDATA #REQUIRED
                question_id CDATA #REQUIRED
                user_id CDATA #REQUIRED>

        <!ELEMENT question (#PCDATA)>
        <!ATTLIST question
                id CDATA #REQUIRED
                description CDATA #REQUIRED
                is_deleted CDATA #REQUIRED
                last_redaction_date CDATA #REQUIRED
                persist_date CDATA #REQUIRED
                title CDATA #REQUIRED
                user_id CDATA #REQUIRED>

        <!ELEMENT role (#PCDATA)>
        <!ATTLIST role
                id CDATA #REQUIRED
                name CDATA #REQUIRED>

=== JavaDim/stackkataproject/src/test/resources/datasets/testresourceusercontroller/dataset.xml
<!DOCTYPE dataset SYSTEM "src/test/resources/datasets/testresourceusercontroller/database.dtd">

<dataset>
    <user_entity id="100" about="test user 1" city="Medina" email="bill@mail.ru" full_name="Bill Gates"
                 image_link="test image link" is_deleted="false" is_enabled="true"
                 last_redaction_date="2022-07-29 14:02:02.030177"
                 link_github="github@bill.gates" link_site="microsoft.com" link_vk="vk.com/bill"
                 nickname="Trey" password="pass"
                 persist_date="2022-07-28 14:02:02.030177" role_id="100"/>
    <user_entity id="101" about="test user 2" city="Austin" email="elon@mail.ru" full_name="Elon Musk"
                 image_link="test image link" is_deleted="false" is_enabled="true"
                 last_redaction_date="2022-07-29 14:02:02.030177"
                 link_github="github@elon.musk" link_site="tesla.com" link_vk="vk.com/elon"
                 nickname="TechnoKing" password="pass"
                 persist_date="2022-07-28 14:02:02.030177" role_id="101"/>

    <answer id="100" date_accept_time="2022-07-29 14:02:02.030177" html_body="html" is_deleted="false"
            is_deleted_by_moderator="false" is_helpful="true" persist_date="2022-07-29 14:02:02.030177"
            update_date="2022-07-29 14:02:02.030177" question_id="100" user_id="101"/>

    <question id="100" description="question" is_deleted="false" last_redaction_date="2022-07-29 14:02:02.030177"
              persist_date="2022-07-29 14:02:02.030177" title="question" user_id="101"/>

    <reputation id="100" count="5" persist_date="2022-07-29 14:02:02.030177" type="1" answer_id="100" author_id="100" question_id="100" sender_id="101"/>
    <reputation id="101" count="5" persist_date="2022-07-29 14:02:02.030177" type="1" answer_id="100" author_id="100" question_id="100" sender_id="101"/>
    <reputation id="102" count="5" persist_date="2022-07-29 14:02:02.030177" type="1" answer_id="100" author_id="101" question_id="100" sender_id="100"/>

    <votes_on_answers id="100" persist_date="2022-07-29 14:02:02.030177" vote_type="UP" answer_id="100" user_id="100"/>
    <votes_on_answers id="101" persist_date="2022-07-29 14:02:02.030177" vote_type="UP" answer_id="100" user_id="101"/>
    <votes_on_answers id="102" persist_date="2022-07-29 14:02:02.030177" vote_type="DOWN" answer_id="100" user_id="101"/>
    <votes_on_answers id="103" persist_date="2022-07-29 14:02:02.030177" vote_type="UP" answer_id="100" user_id="101"/>

    <votes_on_questions id="100" persist_date="2022-07-29 14:02:02.030177" vote_typeq="UP" question_id="100" user_id="100"/>
    <votes_on_questions id="101" persist_date="2022-07-29 14:02:02.030177" vote_typeq="DOWN" question_id="100" user_id="100"/>
    <votes_on_questions id="102" persist_date="2022-07-29 14:02:02.030177" vote_typeq="DOWN" question_id="100" user_id="101"/>
    <votes_on_questions id="103" persist_date="2022-07-29 14:02:02.030177" vote_typeq="UP" question_id="100" user_id="101"/>

    <role id="100" name="ADMIN"/>
    <role id="101" name="USER"/>
</dataset>
